export const testCatalog = [
  {
    file: 'src/data/content.test.js',
    group: 'portfolio content',
    name: 'lists every project with a title, tags, and status',
    does: 'Locks the five project titles in order and requires tags plus status live on each.',
  },
  {
    file: 'src/data/content.test.js',
    group: 'portfolio content',
    name: 'lists every experience role with a company and period',
    does: 'Locks the four companies in order and requires a role and period on each job.',
  },
  {
    file: 'src/data/content.test.js',
    group: 'portfolio content',
    name: 'lists skill categories, certifications, and languages',
    does: 'Checks stack category names, that Software Architect is listed, and the four languages.',
  },
  {
    file: 'src/data/content.test.js',
    group: 'portfolio content',
    name: 'keeps identity, contact, and nav links in one profile module',
    does: 'Checks email, LinkedIn URL, phone tel: link, site/GitHub URLs, and nav hashes stay in profile data.',
  },
  {
    file: 'src/data/content.test.js',
    group: 'portfolio content',
    name: 'ships the resume PDF linked from the profile at the public path',
    does: 'Asserts public/ZakariaAhmadResume.pdf exists and is a PDF for the Nav download link.',
  },
  {
    file: 'src/data/content.test.js',
    group: 'portfolio content',
    name: 'keeps SEO markup aligned with profile site and GitHub URLs',
    does: 'Asserts index.html canonical/OG/JSON-LD URLs and identity match profile.siteUrl, githubUrl, name, and email.',
  },
  {
    file: 'src/components/projectMedia.test.js',
    group: 'buildMediaItems',
    name: 'returns an empty list when the project has no video or screenshots',
    does: 'Gallery helper returns [] when media is missing or screenshots is empty.',
  },
  {
    file: 'src/components/projectMedia.test.js',
    group: 'buildMediaItems',
    name: 'puts the demo video first, then screenshots in order',
    does: 'Video is item 0; screenshots follow in the given order.',
  },
  {
    file: 'src/components/projectMedia.test.js',
    group: 'buildMediaItems',
    name: 'returns only screenshots when there is no video',
    does: 'Screenshot-only projects become image items with no video entry.',
  },
  {
    file: 'src/components/projectMedia.test.js',
    group: 'buildMediaItems',
    name: 'returns only the video when screenshots are missing',
    does: 'Video-only projects become a single video item.',
  },
  {
    file: 'src/App.test.jsx',
    group: 'App',
    name: 'assembles the main landmark sections',
    does: 'Renders About immediately; waits for lazy Projects, Skills, Contact, plus Back to top.',
  },
  {
    file: 'src/components/Hero.test.jsx',
    group: 'Hero',
    name: 'renders identity, availability, and primary actions',
    does: 'Shows name, available-for-work badge, photo, View My Work, and the years/companies/projects stats.',
  },
  {
    file: 'src/components/Hero.test.jsx',
    group: 'Hero',
    name: 'prioritizes the hero photo as the LCP image',
    does: 'Sets fetchPriority=high on the hero photo so the browser loads the LCP image first.',
  },
  {
    file: 'src/components/Nav.test.jsx',
    group: 'Nav',
    name: 'renders section links and a resume download',
    does: 'Logo, About/Projects/Skills/Contact, and resume PDF download all point at the profile data.',
  },
  {
    file: 'src/components/Nav.test.jsx',
    group: 'Nav',
    name: 'toggles the mobile menu from the burger button',
    does: 'Burger opens the menu; clicking a section link closes it.',
  },
  {
    file: 'src/components/About.test.jsx',
    group: 'About',
    name: 'renders the experience timeline companies and roles',
    does: 'Experience heading plus every company and job title from the data.',
  },
  {
    file: 'src/components/Projects.test.jsx',
    group: 'Projects',
    name: 'renders the portfolio section and every current project',
    does: 'Portfolio heading plus a card heading for each project in the data.',
  },
  {
    file: 'src/components/Projects.test.jsx',
    group: 'Projects',
    name: 'marks private repos and the live portfolio without fake external links',
    does: 'Shows Private Repo and You\'re here, and includes the Firehouse live-site URL.',
  },
  {
    file: 'src/components/Projects.test.jsx',
    group: 'Projects',
    name: 'opens the Firehouse lightbox from the preview image',
    does: 'Clicking the Firehouse preview opens the lightbox with that project title.',
  },
  {
    file: 'src/components/Skills.test.jsx',
    group: 'Skills',
    name: 'renders stack categories, certifications, and languages',
    does: 'Category names, sample skills, every certification title, and every language.',
  },
  {
    file: 'src/components/Contact.test.jsx',
    group: 'Contact',
    name: 'renders contact channels',
    does: 'Mail, LinkedIn, and phone links use the profile values.',
  },
  {
    file: 'src/components/Lightbox.test.jsx',
    group: 'Lightbox',
    name: 'shows the project title and starts on the requested media item',
    does: 'Opens on screenshot 1 when startIndex is 1.',
  },
  {
    file: 'src/components/Lightbox.test.jsx',
    group: 'Lightbox',
    name: 'moves to the next and previous items',
    does: 'Next/Previous buttons change the visible image.',
  },
  {
    file: 'src/components/Lightbox.test.jsx',
    group: 'Lightbox',
    name: 'closes from the close button and from Escape',
    does: 'Close button and Escape both call onClose.',
  },
  {
    file: 'src/components/Lightbox.test.jsx',
    group: 'Lightbox',
    name: 'navigates with arrow keys',
    does: 'ArrowRight/ArrowLeft change the visible image.',
  },
  {
    file: 'src/components/Lightbox.test.jsx',
    group: 'Lightbox',
    name: 'plays the demo when navigating onto a video item',
    does: 'Moving onto the demo video calls play().',
  },
  {
    file: 'src/components/Lightbox.test.jsx',
    group: 'Lightbox',
    name: 'renders nothing when the project has no media',
    does: 'No lightbox markup if the project has neither video nor screenshots.',
  },
  {
    file: 'src/components/Lightbox.test.jsx',
    group: 'Lightbox',
    name: 'hides prev/next controls when there is only one media item',
    does: 'Single-image galleries do not show Next/Previous.',
  },
  {
    file: 'src/test/analytics.test.js',
    group: 'Cloudflare Web Analytics',
    name: 'relies on Automatic injection instead of a manual beacon',
    does: 'Keeps the manual Cloudflareinsights beacon out of index.html so proxied Automatic RUM is the only property.',
  },
  {
    file: 'src/test/cdn.test.js',
    group: 'Cloudflare CDN origin headers',
    name: 'caches public photos, videos, and the resume PDF at the edge',
    does: 'vercel.json matches /:path*.(avif|…) and sets a 30-day Cache-Control so Cloudflare can cache them.',
  },
  {
    file: 'src/test/cdn.test.js',
    group: 'Cloudflare CDN origin headers',
    name: 'caches hashed Vite assets as immutable',
    does: 'Hashed /assets files get a one-year immutable Cache-Control header.',
  },
  {
    file: 'src/test/runbook.test.js',
    group: 'availability runbook',
    name: 'documents UptimeRobot detect and Vercel rollback recover steps',
    does: 'Keeps RUNBOOK.md with UptimeRobot monitoring, Full strict SSL, and Vercel rollback instructions.',
  },
  {
    file: 'src/test/runbook.test.js',
    group: 'scalability (edge cache)',
    name: 'documents purge-after-deploy and spike response using existing CDN headers',
    does: 'Locks RUNBOOK spike/purge guidance to vercel.json media and /assets Cache-Control rules.',
  },
  {
    file: 'src/test/lcp.test.js',
    group: 'LCP image preload',
    name: 'preloads the hero photo before the React module runs',
    does: 'index.html preloads /personal-photo.avif with fetchpriority=high before the app bundle.',
  },
  {
    file: 'src/test/lcp.test.js',
    group: 'LCP font and JS critical path',
    name: 'loads Inter and Space Mono from HTML without a CSS @import',
    does: 'Fonts load via an HTML stylesheet link with only used weights; CSS must not @import Google Fonts.',
  },
  {
    file: 'src/test/lcp.test.js',
    group: 'LCP font and JS critical path',
    name: 'preconnects to Google Fonts before the stylesheet',
    does: 'fonts.googleapis.com and fonts.gstatic.com preconnect before the css2 stylesheet.',
  },
  {
    file: 'src/test/lcp.test.js',
    group: 'LCP font and JS critical path',
    name: 'defers Projects, Skills, and Contact behind React.lazy',
    does: 'Below-fold sections are lazy() imports wrapped in Suspense so they leave the first JS download.',
  },
  {
    file: 'src/test/lcp.test.js',
    group: 'LCP font and JS critical path',
    name: 'does not modulepreload deferred chunks on first paint',
    does: 'vite build.modulePreload is false so async chunks are not preloaded during first paint.',
  },
  {
    file: 'src/test/report.test.js',
    group: 'test catalog',
    name: 'documents every characterizing test in the catalog',
    does: 'Fails if a new it(...) test is added without a catalog entry (or the reverse).',
  },
  {
    file: 'src/test/report.test.js',
    group: 'test catalog',
    name: 'lists every catalog test in TEST_REPORT.md',
    does: 'Fails if TEST_REPORT.md is missing a catalog test name or its summary.',
  },
]
